#!/usr/bin/env bash
set -e

echo "Building the example site..."
bundle exec jekyll build

if test -e "./_site/index.html";then
  echo "It builds!"
  rm -Rf _site
else
  echo "Huh. That's odd. The example site doesn't seem to build."
  exit 1
fi

echo "Running html proofer..."
bundle exec htmlproofer ./_site